version: '3.9'

services:
  # elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - node.name=es01
      - xpack.security.enabled=false # if use don't use ssl/tls , add this line , if not add this line , show error when test  curl -X GET http://localhost:9200
      - cluster.name=elk-cluster
      - ELASTIC_PASSWORD=password
    volumes:
      - ./elasticsearch/config/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yaml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "--silent", "--insecure", "-u", "elastic:password", "http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5600:9200"
    networks:
      - elk-net

  # logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:9.2.2
    container_name: logstash
    environment:
      - ELASTIC_PASSWORD=password
    volumes:
      - ./logstash/config/logstash.yaml:/usr/share/logstash/config/logstash.yaml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./app/logs:/usr/share/logstash/logs
    ports:
      - "5061:9600"
    networks:
      - elk-net
    depends_on:
      elasticsearch:
        condition: service_healthy

  # kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.2
    container_name: kibana
    environment:
      - ELASTIC_PASSWORD=password
    volumes:
      - ./kibana/config/kibana.yaml:/usr/share/kibana/config/kibana.yaml
    ports:
      - "5602:5601"
    networks:
      - elk-net
    depends_on:
      elasticsearch:
        condition: service_healthy

  #kafka
  kafka:
    image: confluentinc/cp-kafka:7.8.0
    hostname: kafka
    container_name: kafka
    networks:
      - kafka-net
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://kafka:29092, EXTERNAL://0.0.0.0:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092 # for external client communication
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT, EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093 # quorum voter for the controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # single replica
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: "/var/lib/kafka/data" # data directory for kafka logs
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data # persist kafka data
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-cluster-ui
    ports:
      - "80:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka
    networks:
      - kafka-net
networks:
  elk-net:
    driver: bridge
  kafka-net:
    driver: bridge
volumes:
  kafka_data: